apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-porto-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/HaikalRFadhilahh/react-porto.git
    targetRevision: HEAD
    path: k8s/production
  destination: 
    server: https://kubernetes.default.svc
    namespace: react-porto

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true