name: Docker Image CI

on:
  pull_request:
    branches: ["master"]

env:
  DOCKER_REGISTRY: ghcr.io
  TAG: ci-test
  IMAGE_NAME: haikalrfadhilahh/haik-react-portofolio

jobs:
  # Build Dockerfile
  Docker_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ke Repository PR
        uses: actions/checkout@v4

      - name: Check Docker Build Docker Images
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
