name: Build Docker Image and Push To Github Container Registry

on:
  # workflow_run:
  #   workflows: ["Docker Image CI"]
  #   types:
  #     - completed
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY: ghcr.io
  TAG: ${{ vars.VERSION }}.${{ github.run_number }}
  IMAGE_NAME: haikalrfadhilahh/haik-react-portofolio

jobs:
  Build_Docker_Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Docker Build Docker Images
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Tagging For Latest Version
        run: docker tag ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin

      - name: Push Docker Image Version
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker Image Latest Version
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
